name: CI/CD Demo

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fake Build Step
        run: echo "Building project..."

      - name: Fake Test Step
        run: echo "Running tests... ✅"

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging (placeholder)
        run: echo "Deploying to STAGING server..."

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production (placeholder)
        run: echo "Deploying to PRODUCTION server..."
